Update README.md
firebase/FirebaseUI pull request #4
Opened 2016-09-28 22:14 UTC by katfang

@abehaskins Adding UI flows for Auth for Android, iOS, and Web.

2016-09-28 22:16 UTC, katfang commented
I signed it!

2016-09-28 22:40 UTC, morganchen12 requested changes
Thanks for doing this work @katfang!

2016-09-28 22:40 UTC, morganchen12 commented on README.md
> +FirebaseUI is available in:
Can you change `in` ->`on`? I think it sounds better (FirebaseUI is available on $platform vs FirebaseUI is available in $platform)

2016-09-28 22:40 UTC, morganchen12 commented on README.md
> +* bindings for `UITableViews` and `UICollectionVIews` on iOs through custom Data Sources.
Capitalization:

>... `UICollectionViews` on iOS through ...

2016-09-28 22:40 UTC, morganchen12 commented on README.md
> +[Firebase Auth UI](https://github.com/firebase/FirebaseUI-iOS/tree/master/FirebaseAuthUI) | UI flows for Authentication
These feature sections are relatively unmaintained, and I can see them falling out of sync with the iOS and Android source repos again in the near future, so I won't worry too much about them in this PR.

2016-09-28 23:09 UTC, katfang commented
@morganchen12 Hmm, I'm not familiar with this change request system ... I attempted to just edit the file and commit changes, but I can't tell if I'm supposed to be able to close out the requests ... but I made the changes. :)

2016-09-28 23:32 UTC, morganchen12 requested changes

2016-09-28 23:32 UTC, morganchen12 commented on README.md
>  FirebaseUI: Simplyify Mobile Development with Firebase
This typo isn't yours, but can you correct it anyway? `Simplyify` -> `Simplify` 😅

Also, FirebaseUI is now beyond mobile, so maybe this whole header should be

>FirebaseUI: Simplifying App Development with Firebase

2016-09-28 23:32 UTC, morganchen12 commented on README.md
> +FirebaseUI is a library that provides common UI elements when building apps. This includes a
Can you change these lines to 

>FirebaseUI is a library that [...] common UI elements when building apps **with Firebase**. This includes
> * **a** basic Auth flow [...]
> * [...]

2016-09-28 23:32 UTC, morganchen12 commented on README.md
> +* bindings for `UITableViews` and `UICollectionViews` on iOs through custom Data Sources.
Capitalize the S in iOS here.

>... on **iOS** through custom Data Sources.

2016-09-29 00:06 UTC, katfang commented
@morganchen12 Changes made. :)

2016-09-29 00:41 UTC, morganchen12 commented on README.md
> +FirebaseUI is a library that provides common UI elements when building apps. This includes a
Delete redundant `a` at the end of this line.

>[...] This includes ~~a~~

After this change, feel free to go ahead and merge. The rest looks good.

2016-09-30 19:21 UTC, katfang commented on README.md
> +FirebaseUI is a library that provides common UI elements when building apps. This includes a
Thanks! :)

2016-09-30 19:21 UTC, merged